# Generated by Django 5.0.14 on 2026-02-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0002_setup_timescaledb_hypertables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImbalanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alert_type', models.CharField(choices=[('high_bid_pressure', 'High Bid Pressure'), ('high_ask_pressure', 'High Ask Pressure'), ('extreme_imbalance', 'Extreme Imbalance'), ('liquidity_hole', 'Liquidity Hole')], max_length=30)),
                ('imbalance_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bid_depth', models.DecimalField(decimal_places=8, max_digits=30)),
                ('ask_depth', models.DecimalField(decimal_places=8, max_digits=30)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imbalance_alerts', to='market_data.symbol')),
            ],
            options={
                'db_table': 'imbalance_alert',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='imbalance_a_symbol__fcc1d9_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='imbalance_a_alert_t_efacba_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderbookAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('mid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_absolute', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_bps', models.DecimalField(decimal_places=4, help_text='Spread in basis points (0.01%)', max_digits=10)),
                ('bid_depth_10', models.DecimalField(decimal_places=8, help_text='Total bid volume in top 10 levels', max_digits=30)),
                ('ask_depth_10', models.DecimalField(decimal_places=8, help_text='Total ask volume in top 10 levels', max_digits=30)),
                ('total_depth_10', models.DecimalField(decimal_places=8, max_digits=30)),
                ('imbalance_ratio', models.DecimalField(decimal_places=4, help_text='bid_depth / (bid_depth + ask_depth)', max_digits=10)),
                ('imbalance_pct', models.DecimalField(decimal_places=4, help_text='(bid_depth - ask_depth) / total_depth * 100', max_digits=10)),
                ('vwap_buy_1000', models.DecimalField(blank=True, decimal_places=8, help_text='Estimated VWAP for buying $1000 worth', max_digits=20, null=True)),
                ('vwap_sell_1000', models.DecimalField(blank=True, decimal_places=8, help_text='Estimated VWAP for selling $1000 worth', max_digits=20, null=True)),
                ('liquidity_score', models.DecimalField(blank=True, decimal_places=4, help_text='Composite liquidity score (0-100)', max_digits=10, null=True)),
                ('has_liquidity_hole', models.BooleanField(default=False, help_text='True if large gap detected in orderbook')),
                ('levels_analyzed', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbook_analysis', to='market_data.symbol')),
            ],
            options={
                'db_table': 'orderbook_analysis',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='orderbook_a_symbol__d0fee0_idx'), models.Index(fields=['timestamp'], name='orderbook_a_timesta_e34603_idx'), models.Index(fields=['imbalance_ratio'], name='orderbook_a_imbalan_a5414f_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
