# Generated by Django 5.0.14 on 2026-02-16 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('TRADING', 'Trading'), ('BREAK', 'Break'), ('HALT', 'Halt'), ('AUCTION_MATCH', 'Auction Match')], default='TRADING', max_length=20)),
                ('is_spot', models.BooleanField(default=True)),
                ('is_futures', models.BooleanField(default=False)),
                ('listing_date', models.DateTimeField(blank=True, null=True)),
                ('delisting_date', models.DateTimeField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('step_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_tracked', models.BooleanField(default=True, help_text='Whether to actively ingest data for this symbol')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority symbols get ingested more frequently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_data_symbol',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['name'], name='market_data_name_b4f74e_idx'), models.Index(fields=['is_tracked', 'priority'], name='market_data_is_trac_8603bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('bids', models.JSONField(help_text='List of [price, quantity] bid levels')),
                ('asks', models.JSONField(help_text='List of [price, quantity] ask levels')),
                ('mid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread_bps', models.DecimalField(blank=True, decimal_places=4, help_text='Spread in basis points', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbook_snapshots', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_orderbook_snapshot',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__05f417_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_2fae43_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_interest', models.DecimalField(decimal_places=8, help_text='Open interest in base asset', max_digits=30)),
                ('open_interest_value', models.DecimalField(blank=True, decimal_places=8, help_text='Open interest in USDT', max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_interest_data', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_open_interest',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__3524e5_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_ef7428_idx')],
            },
        ),
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('3m', '3 minutes'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('2h', '2 hours'), ('4h', '4 hours'), ('6h', '6 hours'), ('8h', '8 hours'), ('12h', '12 hours'), ('1d', '1 day'), ('3d', '3 days'), ('1w', '1 week'), ('1M', '1 month')], max_length=5)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('close_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('trades_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('taker_buy_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('taker_buy_quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_kline',
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='market_data_symbol__72d75f_idx'), models.Index(fields=['open_time'], name='market_data_open_ti_33f3bd_idx')],
                'unique_together': {('symbol', 'interval', 'open_time')},
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('kline', 'Kline'), ('trade', 'Trade'), ('orderbook', 'OrderBook'), ('ticker', 'Ticker'), ('funding_rate', 'Funding Rate'), ('open_interest', 'Open Interest')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_ingestion_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'data_type', 'status'], name='market_data_symbol__8e795e_idx'), models.Index(fields=['created_at'], name='market_data_created_b690e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('funding_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('funding_time', models.DateTimeField()),
                ('mark_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rates', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_funding_rate',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__033dc8_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_6fd381_idx')],
                'unique_together': {('symbol', 'funding_time', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Ticker24h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_change', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_change_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('weighted_avg_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trades_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_snapshots', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_ticker24h',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__351ffa_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_8bb8e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quote_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_buyer_maker', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.symbol')),
            ],
            options={
                'db_table': 'market_data_trade',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__14a179_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_254335_idx')],
                'unique_together': {('symbol', 'trade_id', 'timestamp')},
            },
        ),
    ]
