# Generated by Django 5.0.14 on 2026-02-16 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0002_setup_timescaledb_hypertables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy Signal'), ('sell', 'Sell Signal'), ('neutral', 'Neutral')], max_length=20)),
                ('strength', models.IntegerField(default=50, help_text='Signal strength 1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('intervals', models.JSONField(default=list, help_text="List of intervals, e.g. ['1h', '4h']")),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbols', models.ManyToManyField(blank=True, help_text='Leave empty for all symbols', to='market_data.symbol')),
            ],
            options={
                'db_table': 'analysis_signal_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ema_9', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ema_21', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ema_50', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ema_100', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ema_200', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_20', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('macd_diff', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('adx', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('adx_pos', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('adx_neg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stoch_k', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stoch_d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('williams_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bb_high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bb_mid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bb_low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bb_width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('atr', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('vwap', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('obv', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('hull_ma', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('supertrend', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('supertrend_direction', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market_data.symbol')),
            ],
            options={
                'db_table': 'analysis_indicator_cache',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'timestamp'], name='analysis_in_symbol__36e2e5_idx'), models.Index(fields=['timestamp'], name='analysis_in_timesta_4baa5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatternDetection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interval', models.CharField(max_length=5)),
                ('pattern_type', models.CharField(choices=[('doji', 'Doji'), ('hammer', 'Hammer'), ('inverted_hammer', 'Inverted Hammer'), ('hanging_man', 'Hanging Man'), ('shooting_star', 'Shooting Star'), ('engulfing_bullish', 'Bullish Engulfing'), ('engulfing_bearish', 'Bearish Engulfing'), ('morning_star', 'Morning Star'), ('evening_star', 'Evening Star'), ('three_white_soldiers', 'Three White Soldiers'), ('three_black_crows', 'Three Black Crows'), ('double_top', 'Double Top'), ('double_bottom', 'Double Bottom'), ('head_shoulders', 'Head and Shoulders'), ('inverse_head_shoulders', 'Inverse Head and Shoulders'), ('triangle_ascending', 'Ascending Triangle'), ('triangle_descending', 'Descending Triangle'), ('triangle_symmetrical', 'Symmetrical Triangle'), ('flag_bullish', 'Bullish Flag'), ('flag_bearish', 'Bearish Flag')], max_length=50)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('reliability', models.IntegerField(help_text='Pattern reliability score 1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price_at_detection', models.DecimalField(decimal_places=8, max_digits=20)),
                ('support_level', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('resistance_level', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional pattern-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='market_data.symbol')),
            ],
            options={
                'db_table': 'analysis_pattern_detection',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analysis_pa_symbol__5d7ee7_idx'), models.Index(fields=['pattern_type', 'direction'], name='analysis_pa_pattern_7e870b_idx'), models.Index(fields=['timestamp'], name='analysis_pa_timesta_bd3610_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interval', models.CharField(max_length=5)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('strong_buy', 'Strong Buy'), ('strong_sell', 'Strong Sell'), ('neutral', 'Neutral')], max_length=20)),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price_at_signal', models.DecimalField(decimal_places=8, max_digits=20)),
                ('indicators_snapshot', models.JSONField(default=dict, help_text='Snapshot of key indicators at signal time')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0-100', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market_data.symbol')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_signals', to='analysis.signalrule')),
            ],
            options={
                'db_table': 'analysis_signal',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analysis_si_symbol__4dc467_idx'), models.Index(fields=['signal_type', 'is_active'], name='analysis_si_signal__de08d3_idx'), models.Index(fields=['timestamp'], name='analysis_si_timesta_0f518a_idx')],
            },
        ),
    ]
