# Generated by Django 5.0.14 on 2026-02-16 17:40

from django.db import migrations


def setup_timescaledb(apps, schema_editor):
    """Setup TimescaleDB hypertables for analysis app"""
    
    with schema_editor.connection.cursor() as cursor:
        # 1. IndicatorCache hypertable
        cursor.execute("""
            SELECT create_hypertable(
                'analysis_indicator_cache',
                'timestamp',
                if_not_exists => TRUE,
                migrate_data => TRUE,
                chunk_time_interval => INTERVAL '1 day'
            );
        """)
        
        # Enable compression for IndicatorCache
        cursor.execute("""
            ALTER TABLE analysis_indicator_cache SET (
                timescaledb.compress,
                timescaledb.compress_segmentby = 'symbol_id,interval'
            );
        """)
        
        cursor.execute("""
            SELECT add_compression_policy(
                'analysis_indicator_cache', 
                INTERVAL '7 days',
                if_not_exists => TRUE
            );
        """)
        
        # 2. Signal hypertable
        cursor.execute("""
            SELECT create_hypertable(
                'analysis_signal',
                'timestamp',
                if_not_exists => TRUE,
                migrate_data => TRUE,
                chunk_time_interval => INTERVAL '1 day'
            );
        """)
        
        # Enable compression for Signal
        cursor.execute("""
            ALTER TABLE analysis_signal SET (
                timescaledb.compress,
                timescaledb.compress_segmentby = 'symbol_id,signal_type'
            );
        """)
        
        cursor.execute("""
            SELECT add_compression_policy(
                'analysis_signal',
                INTERVAL '7 days',
                if_not_exists => TRUE
            );
        """)
        
        # 3. PatternDetection hypertable
        cursor.execute("""
            SELECT create_hypertable(
                'analysis_pattern_detection',
                'timestamp',
                if_not_exists => TRUE,
                migrate_data => TRUE,
                chunk_time_interval => INTERVAL '1 day'
            );
        """)
        
        # Enable compression for PatternDetection
        cursor.execute("""
            ALTER TABLE analysis_pattern_detection SET (
                timescaledb.compress,
                timescaledb.compress_segmentby = 'symbol_id,pattern_type'
            );
        """)
        
        cursor.execute("""
            SELECT add_compression_policy(
                'analysis_pattern_detection',
                INTERVAL '7 days',
                if_not_exists => TRUE
            );
        """)


def teardown_timescaledb(apps, schema_editor):
    """Reverse TimescaleDB setup - not implemented as it's complex"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_timescaledb, teardown_timescaledb),
    ]
