# Generated by Django 5.0.14 on 2026-02-16 18:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_setup_timescale'),
        ('market_data', '0002_setup_timescaledb_hypertables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interval', models.CharField(max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, help_text='Total return %', max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Max drawdown %', max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Win rate %', max_digits=5, null=True)),
                ('avg_win', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('avg_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='market_data.symbol')),
            ],
            options={
                'db_table': 'backtest_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('annual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('monthly_return_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_drawdown_duration_days', models.IntegerField(blank=True, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('downside_deviation', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('calmar_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_win', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('largest_win', models.DecimalField(decimal_places=2, max_digits=20)),
                ('largest_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expectancy', models.DecimalField(decimal_places=2, help_text='Average profit per trade', max_digits=20)),
                ('avg_holding_period_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_holding_period_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_consecutive_wins', models.IntegerField(default=0)),
                ('max_consecutive_losses', models.IntegerField(default=0)),
                ('additional_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='backtest.backtestrun')),
            ],
            options={
                'verbose_name_plural': 'Backtest Metrics',
                'db_table': 'backtest_metrics',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('signal_based', 'Signal-Based'), ('indicator', 'Indicator-Based'), ('ml_model', 'ML Model'), ('custom', 'Custom Logic')], default='signal_based', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Strategy-specific parameters')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Starting capital in quote currency', max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Position size as fraction of capital (0.1 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('stop_loss_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss percentage (e.g., 2.00 = 2%)', max_digits=5, null=True)),
                ('take_profit_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Take profit percentage (e.g., 5.00 = 5%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_rules', models.ManyToManyField(blank=True, help_text='Signal rules to use for this strategy', to='analysis.signalrule')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'db_table': 'backtest_strategy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backtest.strategy'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('entry_time', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_signal', models.CharField(blank=True, help_text='Signal that triggered entry', max_length=100)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('signal', 'Exit Signal'), ('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit'), ('end_of_backtest', 'End of Backtest')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_size_quote', models.DecimalField(decimal_places=2, help_text='Position size in quote currency', max_digits=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, help_text='Profit/Loss in quote currency', max_digits=20, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=4, help_text='P&L percentage', max_digits=10, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('exit_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest.backtestrun')),
            ],
            options={
                'db_table': 'backtest_trade',
                'ordering': ['entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('position_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('open_positions', models.JSONField(default=dict, help_text='Current open positions')),
                ('total_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='backtest.backtestrun')),
            ],
            options={
                'db_table': 'backtest_portfolio',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['backtest_run', 'timestamp'], name='backtest_po_backtes_2f45e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['strategy', 'status'], name='backtest_ru_strateg_efc07a_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['symbol', 'interval'], name='backtest_ru_symbol__ba5667_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['created_at'], name='backtest_ru_created_0a005b_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['backtest_run', 'entry_time'], name='backtest_tr_backtes_949944_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['is_open'], name='backtest_tr_is_open_6af479_idx'),
        ),
    ]
